//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AccountingWeb.Models.Domain;

namespace AccountingWeb.Models.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Budget
    {
        public string YearMonth { get; set; }
        public decimal Amount { get; set; }

        public DateTime FirstDay
        {
            get
            {
                return DateTime.ParseExact(YearMonth + "01", "yyyyMMdd", null);
            }
        }

        public DateTime LastDay
        {
            get
            {
                var daysInMonth = DaysInMonth();
                return DateTime.ParseExact(YearMonth + daysInMonth, "yyyyMMdd", null);
            }
        }

        private int DaysInMonth()
        {
            var daysInMonth = DateTime.DaysInMonth(FirstDay.Year, FirstDay.Month);
            return daysInMonth;
        }

        public decimal Days
        {
            get { return DaysInMonth(); }
        }

        public Period CreatePeriod()
        {
            return new Period(FirstDay, LastDay);
        }

        public decimal DailyAmount()
        {
            return Amount / Days;
        }

        public decimal OverlappingAmount(Period period)
        {
            return period.OverlappingDays(CreatePeriod()) * DailyAmount();
        }
    }
}
