//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AccountingWeb.Models.Domain;

namespace AccountingWeb.Models.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Budget
    {
        public string YearMonth { get; set; }
        public decimal Amount { get; set; } 
    }
}
